apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME-deployment
  labels:
    app: $IMAGE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
      - name: $IMAGE_NAME
        image: $DOCKER_IMAGE
        ports:
        - containerPort: 3030
        env:
        - name: RESOURCE_GROUP
          value: $RESOURCE_GROUP
        - name: ACR_NAME
          value: $ACR_NAME
        - name: AKS_CLUSTER
          value: $AKS_CLUSTER
        - name: IMAGE_NAME
          value: $IMAGE_NAME
        - name: IMAGE_TAG
          value: $IMAGE_TAG
        - name: DEPLOYMENT_FILE
          value: $DEPLOYMENT_FILE
---
apiVersion: v1
kind: Service
metadata:
  name: $IMAGE_NAME-service
spec:
  selector:
    app: $IMAGE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: LoadBalancer
