apiVersion: apps/v1
kind: Deployment
metadata:
  name: cotechnoe-jena-fuseki-deployment
  labels:
    app: cotechnoe-jena-fuseki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cotechnoe-jena-fuseki
  template:
    metadata:
      labels:
        app: cotechnoe-jena-fuseki
    spec:
      containers:
      - name: cotechnoe-jena-fuseki
        image: acrfusekidev.azurecr.io/cotechnoe-jena-fuseki:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3030
        env:
        - name: RESOURCE_GROUP
          value: rg-fuseki-dev
        - name: ACR_NAME
          value: acrfusekidev
        - name: AKS_CLUSTER
          value: aks-fuseki-dev
        - name: IMAGE_NAME
          value: cotechnoe-jena-fuseki
        - name: IMAGE_TAG
          value: latest
        - name: DEPLOYMENT_FILE
          value: deployment.yaml
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cotechnoe-jena-fuseki-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cotechnoe-jena-fuseki-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
