apiVersion: apps/v1
kind: Deployment
metadata:
  name: $IMAGE_NAME-deployment
  labels:
    app: $IMAGE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $IMAGE_NAME
  template:
    metadata:
      labels:
        app: $IMAGE_NAME
    spec:
      containers:
      - name: $IMAGE_NAME
        image: $DOCKER_IMAGE
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
        - containerPort: 3030
        env:
        - name: RESOURCE_GROUP
          value: $RESOURCE_GROUP
        - name: ACR_NAME
          value: $ACR_NAME
        - name: AKS_CLUSTER
          value: $AKS_CLUSTER
        - name: IMAGE_NAME
          value: $IMAGE_NAME
        - name: IMAGE_TAG
          value: $IMAGE_TAG
        - name: DEPLOYMENT_FILE
          value: $DEPLOYMENT_FILE
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: $IMAGE_NAME-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: $IMAGE_NAME-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
